services:
  kokoro:
    container_name: kokoro
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    ports:
      - "8880:8880"
    networks:
      - agent_network

  livekit:
    container_name: livekit
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
    command: --dev --bind "0.0.0.0" --config /config/livekit.yaml
    volumes:
      - ./livekit.yaml:/config/livekit.yaml
    networks:
      - agent_network

  whisper:
    container_name: whisper
    build:
      context: ./whisper
    volumes:
      - ./data/whisper/data:/data
    ports:
      - "11435:80"
    networks:
      - agent_network

  agent:
    container_name: voice-agent
    build:
      context: ./agent
    environment:
      - LIVEKIT_HOST=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - LIVEKIT_AGENT_PORT=7880
      - OPENAI_API_KEY=no-key-needed
      - GROQ_API_KEY=no-key-needed
      - STT_BASE_URL=http://whisper:80/v1
      - STT_MODEL=Systran/faster-whisper-small
      - LLM_BASE_URL=http://ollama:11434/v1
      - LLM_MODEL=gemma3:4b
      - LLM_TIMEOUT=30
      - TTS_BASE_URL=http://kokoro:8880/v1
      - TTS_MODEL=kokoro
      - TTS_VOICE=af_nova
    depends_on:
      - livekit
      - kokoro
      - whisper
    networks:
      - agent_network

  frontend:
    container_name: voice-fe
    build:
      context: ./voice-assistant-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_LIVEKIT_URL=ws://localhost:7880
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
      - NEXT_PUBLIC_LIVEKIT_API_KEY=devkey
    depends_on:
      - livekit
    networks:
      - agent_network

volumes:
  whisper-data:

networks:
  agent_network:
    driver: bridge